# Utiliser l'image officielle de Node.js
FROM node:14

# Définir le répertoire de travail à /app
WORKDIR /app

# Copier le fichier package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier tous les fichiers du projet dans le conteneur
COPY . .

# Exposer le port 9091
EXPOSE 9091

# Démarrer l'application Node.js
CMD ["node", "build/app.js"]


